name: release


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validation step
        run: |
          python3 -m pip install pre-commit
          pre-commit run -a
      - name: tag and release
        run: |
          tag_version=$(cat version.cfg | awk -F"=" '{ print $2 }')
          git tag $tag_version --force
          git push --tags
